# ------------------------------------------------------------------------------
# Whether a villager can acquire the same trade more than once.
allowDuplicateTrades: false 

# true: The villager can acquire the same trade multiple times.

# false: The villager cannot acquire multiple trades that have an item result 
# of the same type (e.g. A villager cannot have two seperate trades for a 
# DIAMOND_AXE even if they have different costs or different enchantments on 
# the axe).

# ------------------------------------------------------------------------------
# Should villagers be able to learn Vanilla Minecraft trades?
disableVanillaTrades: false

# true: The villager cannot learn any Vanilla Minecraft Trades. This does not
# effect pre-existing trades. If a villager is rerolled then it will lose all
# of it's Vanilla Minecraft trades.

# false: The villager can learn Vanilla Minecraft trades. If a villager is
# rerolled, only the custom trades will be rerolled.

# ------------------------------------------------------------------------------
# Item that you can:
# - right click villagers to reroll their custom trades
# - shift + right click villagers to reset all their trades to vanilla trades 
# requires permission: customvillagertrades.use.rerollitem
tool: CLOCK

# ------------------------------------------------------------------------------
# Requires Vault. This will allow you to use <money> type instead of the
# usual <item stack> type for the result and/or the ingredients of a custom
# trade
enableEconomy: false

# The item that will represent a trade involving your Vault Economy as an
# ingredient or as a result
currencyItem: PAPER

# The strings that goes before and after on the cost on a money item:
# "<currencyPrefix><amount><currencySuffix>"
currencyPrefix: '$'
currencySuffix: ''
