main: online.meinkraft.customvillagertrades.CustomVillagerTrades
name: CustomVillagerTrades
version: 1.0-SNAPSHOT
description: Adds custom villager trades
api-version: 1.18
load: STARTUP
author: Reldeam
website: meinkraft.online
commands:
  enable:
    description: Enables the plugin
    usage: /enable
    permission: customvillagertrades.command.enable
    aliases: cvtenable
  disable:
    description: Disables the plugin
    usage: /disable
    permission: customvillagertrades.command.disable
    aliases: cvtdisable
  reload:
    description: Reloads the plugin
    usage: /reload
    permission: customvillagertrades.command.reload
    aliases: cvtreload
permissions:
  customvillagertrades.command.enable:
    description: Allows use of command, /customvillagertrades:enable
    default: op
  customvillagertrades.command.disable:
    description: Allows use of command, /customvillagertrades:disable
    default: op
  customvillagertrades.command.reload:
    description: Allows use of command, /customvillagertrades:reload
    default: op